import { forwardRef } from "react";
import { type DefaultIconProps } from "../types.js";

export const FilmOutline = forwardRef<SVGSVGElement, DefaultIconProps>(
  ({ width, size, height, ...props }, ref) => {
    return (
      <svg
        viewBox="0 0 512 512"
        xmlns="http://www.w3.org/2000/svg"
        width={width ?? size}
        height={height ?? size}
        ref={ref}
        {...props}
      >
        <rect
          height="320"
          width="416"
          fill="none"
          rx="28"
          ry="28"
          stroke="currentColor"
          strokeLinejoin="round"
          strokeWidth="32"
          x="48"
          y="96"
        />
        <rect
          height="80"
          width="80"
          fill="none"
          rx="28"
          ry="28"
          stroke="currentColor"
          strokeLinejoin="round"
          strokeWidth="32"
          x="384"
          y="336"
        />
        <rect
          height="80"
          width="80"
          fill="none"
          rx="28"
          ry="28"
          stroke="currentColor"
          strokeLinejoin="round"
          strokeWidth="32"
          x="384"
          y="256"
        />
        <rect
          height="80"
          width="80"
          fill="none"
          rx="28"
          ry="28"
          stroke="currentColor"
          strokeLinejoin="round"
          strokeWidth="32"
          x="384"
          y="176"
        />
        <rect
          height="80"
          width="80"
          fill="none"
          rx="28"
          ry="28"
          stroke="currentColor"
          strokeLinejoin="round"
          strokeWidth="32"
          x="384"
          y="96"
        />
        <rect
          height="80"
          width="80"
          fill="none"
          rx="28"
          ry="28"
          stroke="currentColor"
          strokeLinejoin="round"
          strokeWidth="32"
          x="48"
          y="336"
        />
        <rect
          height="80"
          width="80"
          fill="none"
          rx="28"
          ry="28"
          stroke="currentColor"
          strokeLinejoin="round"
          strokeWidth="32"
          x="48"
          y="256"
        />
        <rect
          height="80"
          width="80"
          fill="none"
          rx="28"
          ry="28"
          stroke="currentColor"
          strokeLinejoin="round"
          strokeWidth="32"
          x="48"
          y="176"
        />
        <rect
          height="80"
          width="80"
          fill="none"
          rx="28"
          ry="28"
          stroke="currentColor"
          strokeLinejoin="round"
          strokeWidth="32"
          x="48"
          y="96"
        />
        <rect
          height="160"
          width="256"
          fill="none"
          rx="28"
          ry="28"
          stroke="currentColor"
          strokeLinejoin="round"
          strokeWidth="32"
          x="128"
          y="96"
        />
        <rect
          height="160"
          width="256"
          fill="none"
          rx="28"
          ry="28"
          stroke="currentColor"
          strokeLinejoin="round"
          strokeWidth="32"
          x="128"
          y="256"
        />
      </svg>
    );
  },
);

FilmOutline.displayName = "FilmOutline";
